import type { Metadata } from "next";
import EmployeeTemplate from "@/components/EmployeeTemplate";


export const metadata: Metadata = {
  title: "Tiket Kereta Api",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<EmployeeTemplate>
{children}
</EmployeeTemplate>
  );
}
